1. Import the NUMPY package under the name np.

In [265]:
import numpy as np

2. Print the NUMPY version and the configuration.


In [266]:
print(np.__version__)
print('\n')
print(np.show_config())

1.21.5


blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C
    not found = FMA3,AVX2,AVX512F,A

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

Print "a"

In [267]:
# random: numbers from 0 to 1

a = np.random.random((2, 3, 5))
a

array([[[0.99665841, 0.552931  , 0.52070901, 0.78768825, 0.67412132],
        [0.32966582, 0.57417981, 0.52747982, 0.90371323, 0.15955118],
        [0.60705447, 0.38409249, 0.67032439, 0.91742513, 0.33659867]],

       [[0.61324459, 0.90408711, 0.55483498, 0.39226963, 0.37320384],
        [0.07950703, 0.63165332, 0.55555772, 0.55285246, 0.16555962],
        [0.50018442, 0.42438761, 0.35723476, 0.84606598, 0.08612657]]])

In [268]:
# rand: returns a random float between 0 and 1

a = np.random.rand(2,3,5)
a

array([[[0.83424894, 0.9272398 , 0.10878075, 0.08448082, 0.49681675],
        [0.30142718, 0.80063634, 0.37881555, 0.82319205, 0.5073814 ],
        [0.13294129, 0.15662101, 0.32795335, 0.42556653, 0.11073411]],

       [[0.37813405, 0.97093494, 0.93247813, 0.81667572, 0.96406213],
        [0.19544464, 0.08704708, 0.51558505, 0.145718  , 0.41404777],
        [0.74020229, 0.44676258, 0.93609888, 0.24083954, 0.22128828]]])

In [269]:
## randn 3-dimensional array of random values

a = np.random.randn(2,3,5)
a

array([[[-0.59628927,  1.53847235, -0.3564266 , -1.5476149 ,
         -1.42940402],
        [-0.69444811,  0.49081733, -0.66683114,  0.0091239 ,
         -2.9066596 ],
        [ 1.25022255,  0.63564529, -0.20988564,  1.49652553,
         -0.08077758]],

       [[-0.27790183,  0.4137088 , -0.40535751,  0.30201753,
          1.87269816],
        [-0.28076194, -0.14153888,  0.30856731,  0.05766454,
         -1.44658679],
        [ 0.30044132, -0.5977828 ,  1.49022093,  0.84060214,
          2.22762517]]])

5. Create a 5x2x3 3-dimensional array with all values equaling 1.

Assign the array to variable "b"

Print "b"

In [270]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

7. Do a and b have the same size? How do you prove that in Python code?

In [271]:
a.size == b.size

True

8. Are you able to add a and b? Why or why not?

In [272]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [273]:
## We get an Error when trying to add arrays with different shapes:
## "ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)"

## In order for the operation to work we could reshape one of the arrays
np.add(a,b.reshape(2,3,5))

array([[[ 0.40371073,  2.53847235,  0.6435734 , -0.5476149 ,
         -0.42940402],
        [ 0.30555189,  1.49081733,  0.33316886,  1.0091239 ,
         -1.9066596 ],
        [ 2.25022255,  1.63564529,  0.79011436,  2.49652553,
          0.91922242]],

       [[ 0.72209817,  1.4137088 ,  0.59464249,  1.30201753,
          2.87269816],
        [ 0.71923806,  0.85846112,  1.30856731,  1.05766454,
         -0.44658679],
        [ 1.30044132,  0.4022172 ,  2.49022093,  1.84060214,
          3.22762517]]])

Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c"

In [274]:
c = np.transpose(b, (1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [275]:
c.shape

(2, 3, 5)

10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?

In [276]:
## "a" and "c" have now the same shape (2,3,5)

d = np.add(a,c)
d

array([[[ 0.40371073,  2.53847235,  0.6435734 , -0.5476149 ,
         -0.42940402],
        [ 0.30555189,  1.49081733,  0.33316886,  1.0091239 ,
         -1.9066596 ],
        [ 2.25022255,  1.63564529,  0.79011436,  2.49652553,
          0.91922242]],

       [[ 0.72209817,  1.4137088 ,  0.59464249,  1.30201753,
          2.87269816],
        [ 0.71923806,  0.85846112,  1.30856731,  1.05766454,
         -0.44658679],
        [ 1.30044132,  0.4022172 ,  2.49022093,  1.84060214,
          3.22762517]]])

Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
## Since we add the ones array to the "c" array (now "d"), this new array has now 1.(...) in its values
## different from array "b" where all values are below 1

In [277]:
a

array([[[-0.59628927,  1.53847235, -0.3564266 , -1.5476149 ,
         -1.42940402],
        [-0.69444811,  0.49081733, -0.66683114,  0.0091239 ,
         -2.9066596 ],
        [ 1.25022255,  0.63564529, -0.20988564,  1.49652553,
         -0.08077758]],

       [[-0.27790183,  0.4137088 , -0.40535751,  0.30201753,
          1.87269816],
        [-0.28076194, -0.14153888,  0.30856731,  0.05766454,
         -1.44658679],
        [ 0.30044132, -0.5977828 ,  1.49022093,  0.84060214,
          2.22762517]]])

In [278]:
d

array([[[ 0.40371073,  2.53847235,  0.6435734 , -0.5476149 ,
         -0.42940402],
        [ 0.30555189,  1.49081733,  0.33316886,  1.0091239 ,
         -1.9066596 ],
        [ 2.25022255,  1.63564529,  0.79011436,  2.49652553,
          0.91922242]],

       [[ 0.72209817,  1.4137088 ,  0.59464249,  1.30201753,
          2.87269816],
        [ 0.71923806,  0.85846112,  1.30856731,  1.05766454,
         -0.44658679],
        [ 1.30044132,  0.4022172 ,  2.49022093,  1.84060214,
          3.22762517]]])

Multiply a and c. Assign the result to e.

In [280]:
e = np.multiply(a,c)
e

array([[[-0.59628927,  1.53847235, -0.3564266 , -1.5476149 ,
         -1.42940402],
        [-0.69444811,  0.49081733, -0.66683114,  0.0091239 ,
         -2.9066596 ],
        [ 1.25022255,  0.63564529, -0.20988564,  1.49652553,
         -0.08077758]],

       [[-0.27790183,  0.4137088 , -0.40535751,  0.30201753,
          1.87269816],
        [-0.28076194, -0.14153888,  0.30856731,  0.05766454,
         -1.44658679],
        [ 0.30044132, -0.5977828 ,  1.49022093,  0.84060214,
          2.22762517]]])

Does e equal to a? Why or why not?

In [ ]:
## Yes, because we multiply the "e" array times the values in the "c" array which has all ones.
## Hence the result remains the same

Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [281]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

3.2276251723849847
-1.9066595991567254
1.0532028748615565


Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [282]:
f = np.empty((2,3,5))

16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.

In [283]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if (d_mean>d[i][j][k]>d_min):
                f[i][j][k]=float(25)
            elif (d_max>d[i][j][k]>d_mean):
                f[i][j][k]=float(75)
            elif (d[i][j][k]==d_mean):
                f[i][j][k]=float(50)
            elif (d[i][j][k]==d_max):
                f[i][j][k]=float(100)
            else:
                f[i][j][k]=float(0)
        
print(f)

[[[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25.  25.   0.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  75.  75. 100.]]]


Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

In [289]:
f = np.empty((2,3,5),dtype='object')

for i in range(2):
    for j in range(3):
        for k in range(5):
            if (d_mean>d[i][j][k]>d_min):
                f[i][j][k] =  "B"
            elif (d_max>d[i][j][k]>d_mean):
                f[i][j][k] = "D"
            elif (d[i][j][k]==d_mean):
                f[i][j][k] = "C"
            elif (d[i][j][k]==d_max):
                f[i][j][k] = "E"
            else:
                f[i][j][k] = "A" 
        
print(f)

[[['B' 'D' 'B' 'B' 'B']
  ['B' 'D' 'B' 'B' 'A']
  ['D' 'D' 'B' 'D' 'B']]

 [['B' 'D' 'B' 'D' 'D']
  ['B' 'B' 'D' 'D' 'B']
  ['D' 'B' 'D' 'D' 'E']]]
